BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Hugo Theme Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "Courtney Brown, Brandon Brown, Faizal Mamah: DevOps Engineers"


[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "A DevOps Resource Site Created and Monitored by C18 Holberton School Tulsa DevOps Students"
  cover = "images/devopsLogo.png"
  author = "Courtney Brown, Brandon Brown, Faizal Mamah: DevOps Engineers"
  authorlocation = ""
  authorwebsite = "https://syui.cf/hugo-theme-air"
  bio= "my bio"
  logo = "images/devopsLogo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]
